# Generated by Django 5.2.7 on 2025-11-18 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='en_reparacion',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('espera', 'En espera'), ('reparacion', 'En reparación'), ('listo', 'Listo para entrega')], default='espera', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.mecanico'),
        ),
    ]
